from resunetexplorer.utils import get_submodule_str, get_submodule, get_output_shape, get_number_maps, model_up_to


class ExtractResUNetLayers:
    """Layers extractor class for PyTorch CNN.

        Receives the model from which attributes such as layer structure and feature maps number will be extracted.

        Parameters
        ----------
        model : Pytorch model           

    """

    def __init__(
            self,
            model,
            model_name: str = None
    ):
        self.model = model
        self.model_name = model_name

    def get_layers(self, layers_paths: list):
        """

        Parameters
        ----------
        layers_paths : list
            Contains the paths to the layers.
            e.g. ['encoder.resblock1', 'encoder.resblock2', ...]
        
        Returns
        ----------
        model_metadata: dict
          A dictionary containing the following metadata
            * 'layer': list of str
              The layer struct from model, in other words, the model submodule.
            * 'n_maps': list of int
              The number of feature maps generated by respective layer. 
            * 'layer_path' : list of str
              Contains the paths to respective layers e.g. ['encoder.resblock1', 'encoder.resblock2', ...]
        """
        model_metadata = {
            "layer_path": [],
            "n_maps": [],
            "layer": [],
            "model_name": self.model_name

        }

        for i, path in enumerate(layers_paths):
            # Get desired layer from model
            layer = get_submodule(self.model, path)

            n_maps = get_number_maps(self.model, layer)
            # Dict appending
            model_metadata["layer_path"].append(path)
            model_metadata["n_maps"].append(n_maps)
            model_metadata["layer"].append(layer)

        return model_metadata
